id: AB701B1BE
title: Prayer to the Three Great Stūpas of Kathmandu
type: translation
pechas:
- I5268B38B
- I1DAF56DC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:48:59.600055
  last_modified_at: 2023-01-04 11:48:59.600066
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I5268B38B/D25C: 08E8
  I1DAF56DC/2659: 08E8
